### ISSUE TITLE
yolo-tiny.cfg vs. yolo-baby.cfg

### ISSUE THREAD

**Issue by zayfod** [thtrieu/darktf#11]
Not really an issue but, I wonder what is the difference between the yolo-tiny.cfg vs. yolo-baby.cfg and whether yolo-baby.cfg is supposed to work in darktf revision c9632454 ?

Is yolo-baby.cfg an older style Darknet configuration?

**Comment by thtrieu** [comment]
They're not the same. yolo-tiny.cfg is old and yolo-baby is actually the new tiny-yolo.cfg. Except that I am still working on batch norm layer so it is not going to work for tiny-yolo soon.

I am trying a lot to refactor codes to see if people can help me out on the coding :D

**Comment by zayfod** [comment]
Hey, thanks for the prompt response!

My experience is that yolo-tiny.cfg works today, and yolo-baby does not. Both load, but only yolo-tiny produces actual output. I do not understand what is wrong with yolo-baby.cfg , would you please elaborate a bit?

**Comment by thtrieu** [comment]
@zayfod It's a bit confusing, I'll make it clear:
`yolo-tiny` is the old `yolo-tiny` (183MB)
`yolo-baby` is the new `tiny-yolo` (103MB)
And anything new is not yet implemented, hence your situation :)

**Comment by zayfod** [comment]
OK. Got it. Is there an older version of Darknet, that I can temporarily revert to, that uses the old yolo-tiny (183 MB)?

E.g. revision e6b3006d ?

**Comment by thtrieu** [comment]
New version is compatible to old version. You just have to download the old weights file and old config files https://github.com/thtrieu/darktf/issues/1
