### ISSUE TITLE
Fine tuning 

### ISSUE THREAD

**Issue by moh3th1** [thtrieu/darktf#6]
I have an error while trying to fine tune your model on my data.

**I followed your instructions :** 
First I wrote two classes only for example `good` and `bad` in `Labels.txt` file
and ran the `clean.py` which gave me `parsed.yolotf` 

**for designing the network:**
I copied the `yolo-tiny.cfg` and renamed it to `yolo-2c.cfg` and changed the number of classes `classes=2` and `output= 588` according to the equation in the paper 

**for Initializing the weights :** 
I used `yolo.tiny.weights` file to initialize my network weights and generated new file
`yolo-2c.weights` using this command
`python genw.py tiny 2c`

**for Flowing the graph:** 
I used 
`python main.py --train --model 2c --noload`
and got this error 
![screenshot from 2016-11-08 16-23-45](https://cloud.githubusercontent.com/assets/15180702/20102760/f219ecb8-a5cf-11e6-8495-99b02b005db5.png)

**Comment by Yaffa1607** [comment]
where is the labels.txt file? 
Do we have to create one?

**Comment by thtrieu** [comment]
@moh3th1 I cannot reproduce the exact error using two labels `pottedplant` and `tvmonitor`. Please tell me more about what label(s) are you using? But before doing that please update the code, and notice the new syntax for `genw` is `python genw.py --src tiny --des 2c`
