### ISSUE TITLE
Annotation file type

### ISSUE THREAD

**Issue by murras** [thtrieu/darktf#934]
I have 1000 image files and their annotation (file type txt). They are used in YOLO.

But Darkflow's annotation is required xml file type annotation.

Can I change my txt file to xml easily?

or I have to marking again?

**Comment by murras** [comment]
Can I see your python scripts?

**Comment by joshuasmith44** [comment]
This program read in a large json file and converted into to individual xml files.

**Comment by murras** [comment]
Thank you for your help.

**Comment by AhmadAlhati** [comment]
Have the same case,
and the ann.txt file format after labeling in YOLO format was like this:
as mentioned here (https://github.com/tzutalin/labelImg/blob/master/README.rst)

0 0.928649 0.204563 0.068869 0.082439
1 0.711788 0.300997 0.512090 0.095859
3 0.713515 0.423505 0.487910 0.086273
4 0.866904 0.516296 0.185449 0.079371
2 0.735320 0.744824 0.479706 0.093175
7 0.274072 0.723735 0.263601 0.092408

is the converter.py script mentioned above solve this case?

**Comment by murras** [comment]
http://murra.tistory.com/62?category=685623
I use this code.
Change labels and function convert_label

**Comment by AhmadAlhati** [comment]
thank you for your help..
